name: bus_rapid_transit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^6.0.0
  convex_bottom_bar: ^3.2.0
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Coda
      fonts:
        - asset: assets\fonts\Coda-ExtraBold.ttf
        - asset: assets\fonts\Coda-Regular.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
  assets:
    - assets/images/splash_images/BackgroundShape.png
    - assets/images/splash_images/halfBackgroundShape.png
    - assets/images/splash_images/MinistryLogoContainer.png
    - assets/images/success_screen_images/confetti_component.png
    - assets/images/success_screen_images/Frame.png
    - assets/images/tahrirSquare.png
    - assets/images/OverlayBackground.png
    - assets/images/home_screen_images/Rectangle146.png
    - assets/images/home_screen_images/Rectangle147.png
    - assets/images/home_screen_images/fawry.png
    - assets/images/home_screen_images/rhombus.png
    - assets/images/ticket_images/Ellipse6.png
    - assets/images/ticket_images/Ellipse7.png
    - assets/images/ticket_images/Ellipse8.png
    - assets/images/ticket_images/Ellipse9.png
    - assets/images/ticket_images/qrCode.png
    - assets/images/ticket_images/number.png
    - assets/images/ticket_images/arrows.png
    - assets/fonts/Lalezar-Regular.ttf
    - assets/fonts/Cairo-SemiBold.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/images/image.png
    - assets/fonts/Almarai-Regular.ttf
    - assets/fonts/Almarai-Bold.ttf
    - assets/fonts/Coda-Regular.ttf
    - assets/fonts/Coda-ExtraBold.ttf
    - assets/fonts/Inter_18pt-Bold.ttf

  uses-material-design: true
